#!/bin/bash

# Update package lists
apt-get update

# Install PostgreSQL and its contributions
apt-get install -y postgresql postgresql-contrib

# Create the PostgreSQL user with the name 'postgres' and set the password
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

# Create a new database
sudo -u postgres createdb sakila

# Restore the database from the dump file
sudo -u postgres pg_restore -U postgres -d sakila /home/jovyan/W2D4/data/sakila_backup.dump

# Allow access from localhost
echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/*/main/pg_hba.conf
echo "listen_addresses='*'" >> /etc/postgresql/*/main/postgresql.conf

